# -*- coding: utf-8 -*-
"""modelo de prediccion spotify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9ZiDqLZVNYVS0K_SJKVtonv7u-Yiugz

importamos las librerias necesarias
"""

import pandas as pd
import os

"""Son varias archivos csv que conforman la base de datos entonces en el siguiente código se van a unir en una sola"""

def unir_archivos_csv(archivos_csv, archivo_salida):
    # Crear una lista para almacenar los DataFrames de los archivos CSV
    dfs = []

    # Leer cada archivo CSV y almacenar su contenido en la lista
    for archivo in archivos_csv:
        df = pd.read_csv(archivo)
        dfs.append(df)

    # Concatenar todos los DataFrames en uno solo
    df_final = pd.concat(dfs, ignore_index=True)

    # Escribir el DataFrame final en un nuevo archivo CSV
    df_final.to_csv(archivo_salida, index=False)

    print("Los archivos CSV se han unido exitosamente en", archivo_salida)

# Lista de archivos CSV que se desean unir
archivos_csv = ['dataset-of-00s.csv', 'dataset-of-10s.csv', 'dataset-of-60s.csv','dataset-of-70s.csv','dataset-of-80s.csv','dataset-of-90s.csv']

# Nombre del archivo CSV de salida
archivo_salida = 'spotify.csv'

# Llamar a la función para unir los archivos CSV
unir_archivos_csv(archivos_csv, archivo_salida)

"""Se procede a leer el archivo recien creado y muestra los campos que tiene."""

df = pd.read_csv('spotify.csv', encoding = "utf-8")
df

"""Se imprime la cantidad de archivos que tiene y la cantidad de columnas"""

print('Cantidad de datos')
print(df.shape)

"""Se muestra los tipos de datos que tiene la base de datos"""

print('Tipos de datos')
print(df.info())

"""Aca se verifica si afltan algunos datos."""

print('Datos faltantes: ')
print(pd.isnull(df).sum())

"""Se realiza una ddescripción estadistica de la tabla donde se muestra datos como el maximo, el 75%, 50%, la minima, media, 25% y demás datos."""

print('Estadisticas del dataset')
print(df.describe())

"""Se verifica que no hallan celdas con datos nulos."""

def detectar_datos_nulos(archivo_csv):
    # Leer el archivo CSV en un DataFrame
    df = pd.read_csv(archivo_csv)

    # Comprobar si hay datos nulos en el DataFrame
    if df.isnull().values.any():
        print("Se han detectado datos nulos en el DataFrame:")
        print(df[df.isnull().any(axis=1)])
    else:
        print("No se han detectado datos nulos en el DataFrame.")

# Nombre del archivo CSV que se desea analizar
archivo_csv = 'spotify.csv'

# Llamar a la función para detectar datos nulos en el archivo CSV
detectar_datos_nulos(archivo_csv)